#!/bin/bash

HEALTH=10
COUNT=0
X=0
Y=0
MONSTERPRESENT=0
FIRSTRUN=1
VITALITY=72
telnet_prompt=0

function  move() {
	LOCATION="$X,$Y"
#	echo "$LOCATION"; #DEBUG
	if [ "$LOCATION" == "0,0" ]; then
		echo -e "\e[93mYou're in the temple."
		echo -e "\e[92mThere is a blue robed priest here."
	elif [ "$LOCATION" == "1,0" ]; then
		echo -e "\e[93mYou're in the north plaza."
		echo -e "\e[95mThere is nobody here."
	elif [ "$LOCATION" == "2,0" ]; then
                echo -e "\e[93mYou're in the arena."
                echo -e "\e[95mThere is nobody here."
	elif [ "$LOCATION" == "2,1" ]; then
		echo -e "\e[93mYou're in the tavern."
		echo -e "\e[92mThere is a barkeep, and a barmaid here."
	elif [ "$LOCATION" == "1,1" ]; then
		echo -e "You're in the guild."
	fi
	echo -e "\e[96mThere is nothing on the floor.\e[39m"
}


function simulation() {
case $1 in
he)
echo "
Mana:         0 / 8
Vitality:     $VITALITY / 73
Status:       Healthy
"
	;;
ep)
echo "
Level:        4
Experience:   10305
Rune:         None"
	;;
'ri g')
echo -e "\e[93mYou just rang the great gong!
\e[92mA kobold enters the arena through the dungeon gate!
\e[91mThe kobold attacked Pez2 with his knife!\e[39m"
	VITALITY=$((VITALITY-10))
	MONSTERPRESENT=1
	COUNT=0
	FIRSTRUN=1
	;;
'a kobold'|'a k')
	COUNT=$((COUNT+1))
	if [ $COUNT -le $HEALTH ] && [ $MONSTERPRESENT -eq 1 ]; then
		echo -e "\e[95mYour attack hit the kobold for 4 damage!\e[39m"
	elif [ $MONSTERPRESENT -eq 1 ]; then
		echo -e "\e[93mThe kobold falls to the ground lifeless!"
		echo -e "\e[96mYou found 2 gold crowns while searching the kobold's corpse.\e[39m"
		MONSTERPRESENT=0
	elif [ $FIRSTRUN -eq 1 ]; then
		echo -e "\e[35mYou are still physically exhausted from your previous activities!\e[39m"
		FIRSTRUN=0
	else
		echo -e "\e[35mYou don't see a kobold here.\e[39m"
	fi
	;;
w)
	X=$((X-1))
	if [ $X -lt 0 ]; then
		X=0;
	fi
	move
	;;
e)	X=$((X+1))
	if [ $X -gt 2 ]; then
		X=2
	fi
	move
	;;
n)
	Y=$((Y+1))
	if [ $Y -gt 2 ]; then
		Y=2
	fi
	move
	;;
ne)
	Y=$((Y+1))
	X=$((X+1))
	if [ $Y -gt 2 ]; then
		Y=2
	fi
	if [ $X -gt 2 ]; then
		X=2
	fi
	move
	;;
sw)
	X=$((X-1))
	Y=$((Y-1))
	if [ $X -lt 0 ]; then
		X=0
	fi
	if [ $Y -lt 0 ]; then
		Y=0
	fi
	move
	;;
s)
	Y=$((Y-1))
	if [ $Y -lt 0 ]; then
		Y=0
	fi
	move
	;;

''|l)
	move
	;;
c)
	echo "You confuse the key syllables and the spell fails!"
	;;
'b drink'|'buy drink')
	if [ "$X,$Y" == "2,1" ]; then
		echo -e "\e[96mThe barmaid brings you a drink for 1 crowns.\e[39m"
	else
		echo -e "\e[35mThat item is not offered here.\e[39m"
	fi
	;;
'b healing'|'buy healing')
	if [ "$X,$Y" == "0,0" ]; then
		echo -e "\e[96mThe priests heal all your wounds for 4 crowns.\e[39m"
		VITALITY=73
	else
		echo -e "\e[35mThat item is not offered here.\e[39m"
	fi
	;;
^])
	echo "telnet>"
	telnet_prompt=1
	;;
q)
	if [ $telnet_prompt_last -eq 1 ]; then
		exit
	fi
	;;
esac
}

while [ 0 -eq 0 ]
do
	read INPUT
	simulation "$INPUT"
	telnet_prompt_last=$telnet_prompt
done

